apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guestbook-tls-cert
  namespace: guestbook
spec:
  commonName: guestbook.ne.local
  dnsNames:
  - guestbook.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: guestbook-tls
  usages:
  - server auth
  - client auth